### ISSUE TITLE
2021 Annual Reports Umbrella/Table of Contents

### ISSUE THREAD

**Issue by parispittman** [kubernetes/steering#205]
Using this to keep track of all of the merged SIG and WG community health checks. 

- [x] api-machinery [here](https://github.com/kubernetes/community/blob/master/sig-api-machinery/annual-report-2020.md)
- [x] apps [here](https://github.com/kubernetes/community/blob/master/sig-apps/annual-report-2021.md)
- [x] architecture [here](https://github.com/kubernetes/community/blob/master/sig-architecture/annual-report-2021.md)
- [x] auth [here](https://github.com/kubernetes/community/pull/5740)
- [x] autoscaling (not done: https://github.com/kubernetes/community/pull/5614)
- [x] cli [here](https://github.com/kubernetes/community/blob/master/sig-cli/annual-report-2021.md)
- [x] cloud provider [here](https://github.com/kubernetes/community/blob/master/sig-cloud-provider/2020-annual-report.md)
- [x] cluster-lifecycle [here](https://github.com/kubernetes/community/blob/master/sig-cluster-lifecycle/annual-report-2021.md)
- [x] contributor-experience [here](https://github.com/kubernetes/community/blob/master/sig-contributor-experience/annual-report-2021.md)
- [x] docs [here](https://github.com/kubernetes/community/blob/master/sig-docs/annual-report-2021.md)
- [x] instrumentation [here](https://github.com/kubernetes/community/blob/master/sig-instrumentation/annual-report-2021.md)
- [x] multicluster [here](https://github.com/kubernetes/community/blob/master/sig-multicluster/annual-report-2021.md)
- [x] network (not done: https://github.com/kubernetes/community/pull/5707)
- [x] node [here](https://github.com/kubernetes/community/blob/master/sig-node/annual-report-2021.md)
- [x] release [here](https://github.com/kubernetes/community/blob/master/sig-release/annual-report-2021.md)
- [x] scalability [here](https://github.com/kubernetes/community/blob/master/sig-scalability/annual-report-2021.md)
- [x] scheduling [here](https://github.com/kubernetes/community/blob/master/sig-node/annual-report-2021.md)
- [x] security [here](https://github.com/kubernetes/community/blob/master/sig-security/annual-report-2021.md)
- [ ] servicecatalog (not done: https://github.com/kubernetes/community/pull/5610)
- [x] storage [here](https://github.com/kubernetes/community/blob/master/sig-storage/annual-report-2021.md)
- [ ] testing (not done: https://github.com/kubernetes/community/pull/5612/files)
- [x] ui [here](https://github.com/kubernetes/community/blob/master/sig-ui/annual-report-2021.md)
- [x] usability [here](https://github.com/kubernetes/community/blob/master/sig-usability/annual-report-2021.md)
- [x] windows [here](https://github.com/kubernetes/community/pull/5575)
- [x] multitenancy [here](https://github.com/kubernetes/community/blob/master/wg-multitenancy/2021-annual-report.md)
- [x] data protection [here](https://github.com/kubernetes/community/blob/master/wg-data-protection/annual-report-2021.md)
- [x] k8s-infra [here](https://github.com/kubernetes/community/blob/master/wg-k8s-infra/2020-annual-report.md)
- [x] api expression [here](https://github.com/kubernetes/community/blob/master/wg-api-expression/2020-annual-report.md)

**Comment by xing-yang** [comment]
Hi @parispittman, report for data protection WG is already merged: https://github.com/kubernetes/community/blob/master/wg-data-protection/annual-report-2021.md.  Thanks!

**Comment by dims** [comment]
sig-arch : https://github.com/kubernetes/community/pull/5655
sig-release : https://github.com/kubernetes/community/pull/5698
sig-api-machinery : https://github.com/kubernetes/community/pull/5589
sig-cluster-lifecycle : https://github.com/kubernetes/community/pull/5594
sig-usability : https://github.com/kubernetes/community/pull/5615

**Comment by dims** [comment]
@parispittman we can remove `policy`,  `iot edge`, `component standards` from this list as we did not open issues for them ( cc @cblecker )

**Comment by parispittman** [comment]
we are done here for this edition of the reports; closing

/close
