### ISSUE TITLE
2021 Annual Reports Umbrella

### ISSUE THREAD

**Issue by parispittman** [kubernetes/steering#238]
- [x] api-machinery https://github.com/kubernetes/community/blob/master/sig-api-machinery/annual-report-2021.md 
- [x] apps https://github.com/kubernetes/community/blob/master/sig-apps/annual-report-2021.md 
- [x] architecture https://github.com/kubernetes/community/blob/master/sig-architecture/annual-report-2021.md
- [x] auth https://github.com/kubernetes/community/pull/6469 
- [x] autoscaling (https://github.com/kubernetes/community/pull/6453)
- [x] cli: https://github.com/kubernetes/community/pull/6450
- [ ] cloud provider: https://github.com/kubernetes/community/pull/6489; need to resolve open comments
- [x] cluster-lifecycle https://github.com/kubernetes/community/pull/6458 
- [x] contributor-experience https://github.com/kubernetes/community/blob/master/sig-contributor-experience/annual-report-2021.md
- [x] docs https://github.com/kubernetes/community/blob/master/sig-docs/annual-report-2021.md 
- [ ]  k8s-infra: won't be merged before summary publication https://github.com/kubernetes/community/pull/6465
- [x] instrumentation https://github.com/kubernetes/community/blob/master/sig-instrumentation/annual-report-2021.md 
- [ ] multicluster - need a status
- [ ] network 
- [ ] node - coming end of week 
- [x] release https://github.com/kubernetes/community/blob/master/sig-release/annual-report-2021.md 
- [x] scalability https://github.com/kubernetes/community/blob/master/sig-scalability/annual-report-2021.md 
- [x] scheduling https://github.com/kubernetes/community/blob/master/sig-scheduling/annual-report-2021.md
- [x] security https://github.com/kubernetes/community/pull/6454 
- [ ] servicecatalog - winding down
- [x] storage https://github.com/kubernetes/community/blob/master/sig-storage/annual-report-2021.md 
- [x] testing https://github.com/kubernetes/community/blob/master/sig-testing/annual-report-2021.md 
- [ ] ui: https://github.com/kubernetes/community/pull/6439; comments not resolved 
- [ ] usability 
- [x] windows https://github.com/kubernetes/community/blob/master/sig-windows/annual-report-2021.md 
- [ ] multitenancy https://github.com/kubernetes/community/pull/6598; comments not resolved 
- [x] data protection https://github.com/kubernetes/community/pull/6569
- [x] api expression https://github.com/kubernetes/community/blob/master/wg-api-expression/annual-report-2021.md 
- [ ] iot edge https://github.com/kubernetes/community/pull/6456 
- [ ] reliability https://github.com/kubernetes/community/pull/6508
- [x] structured logging https://github.com/kubernetes/community/blob/master/wg-structured-logging/annual-report-2021.md

**Comment by dims** [comment]
sig-arch is here and ready, will be merging in a week : https://github.com/kubernetes/community/pull/6551

**Comment by parispittman** [comment]
we're done:
https://www.cncf.io/reports/kubernetes-annual-report-2021/

/close
