### ISSUE TITLE
checklist for publishing '21 annual reports summary

### ISSUE THREAD

**Issue by parispittman** [kubernetes/steering#247]
deps:
cncf.io reports site - https://www.cncf.io/reports/kubernetes-annual-report-2021/ 
k8s.dev site

publish/announce:
- [x] K8s.io blog - https://github.com/kubernetes/website/pull/34103 
- [x] dev list and slack channel
- [x] leads list and slack channel
- [x] cncf end user group
- [x] cncf gb mailing list and slack channel
- [x] Tweet (in order): k8scontributors (done -> kubernetes (requested in #social-media on cncf slack) -> cncf (done)
- [ ] Podcasts / ask cncf about other media
- [ ] Our employers

**Comment by parispittman** [comment]
change request process:
submit pulls to the steering repo summary and then a steering member will email changes to CNCF PR to update their Wordpress instance

**Comment by parispittman** [comment]
done 

/close
